# Tools
TOOL_PLINK: "/NAS/data/personal/june_dev/Tools/PLINK/plink "
TOOL_PLINK2: "/NAS/data/personal/june_dev/Tools/PLINK2/plink2 "
TOOL_RSCRIPT: "/NAS/data/personal/june_dev/Tools/R/New/R-4.1.1/Build/bin/Rscript "

# Files
FILE_system_model_IDT_World: "/Resource/Model_EthSEQ_IDT_World.gds"
FILE_system_model_IDT_AFR: "/Resource/Model_EthSEQ_IDT_AFR.gds"
FILE_system_model_IDT_EUR: "/Resource/Model_EthSEQ_IDT_EUR.gds"
FILE_system_model_IDT_AMR: "/Resource/Model_EthSEQ_IDT_AMR.gds"
FILE_system_model_IDT_SAS: "/Resource/Model_EthSEQ_IDT_SAS.gds"
FILE_system_model_IDT_EAS: "/Resource/Model_EthSEQ_IDT_EAS.gds"


# Scripts
SCRIPT_Execute_EthSEQ: "Run_EthSEQmodel.r "
SCRIPT_reformat_VCF: "converter_all_format_vcf_to_EthSEQ_input_vcf.sh "


# Population code
## Super Pop
AFR: "African"
AMR: "American"
EUR: "European"
EAS: "East Asian"
SAS: "South Asian"
## Detail Pop
ASW: "African ancestry in SW USA"
ACB: "African Caribbean in Barbados"
BEB: "Bengali in Bangladesh"
GBR: "British from England and Scotland"
CDX: "Chinese Dai in Xishuangbanna, China"
CLM: "Colombian in Medellín, Colombia"
ESN: "Esan in Nigeria"
FIN: "Finnish in Finland"
GWD: "Gambian in Western Division – Mandinka"
GIH: "Gujarati Indians in Houston, Texas, United States"
CHB: "Han Chinese in Beijing, China"
CHS: "Han Chinese South, China"
IBS: "Iberian populations in Spain"
ITU: "Indian Telugu in the U.K."
JPT: "Japanese in Tokyo, Japan"
KHV: "Kinh in Ho Chi Minh City, Vietnam"
LWK: "Luhya in Webuye, Kenya"
MSL: "Mende in Sierra Leone"
MXL: "Mexican Ancestry in Los Angeles CA United States"
PEL: "Peruvian in Lima, Peru"
PUR: "Puerto Rican in Puerto Rico"
PJL: "Punjabi in Lahore, Pakistan"
STU: "Sri Lankan Tamil in the UK"
TSI: "Toscani in Italia"
YRI: "Yoruba in Ibadan, Nigeria"
CEU: "Utah residents with Northern and Western European ancestry from the CEPH collection"
