TOOL:
  PLINK: "/NAS/data/personal/june_dev/Tools/PLINK/plink"
  PLINK2: "/NAS/data/personal/june_dev/Tools/PLINK2/plink2"
  RSCRIPT: "/NAS/data/personal/june_dev/Tools/R/New/R-4.1.1/Build/bin/Rscript"
GDS:
  World: "/Resource/Model_EthSEQ_IDT_World.gds"
  AFR: "/Resource/Model_EthSEQ_IDT_AFR.gds"
  EUR: "/Resource/Model_EthSEQ_IDT_EUR.gds"
  AME: "/Resource/Model_EthSEQ_IDT_AMR.gds"
  SAS: "/Resource/Model_EthSEQ_IDT_SAS.gds"
  EAS: "/Resource/Model_EthSEQ_IDT_EAS.gds"
SCRIPT:
  R_Execute_EthSEQ: "Run_EthSEQmodel.r"
  SH_Reformat_VCF: "converter_all_format_vcf_to_EthSEQ_input_vcf.sh"
POP_CODE:
  SUPER:
    AFR: "African"
    AMR: "American"
    EUR: "European"
    EAS: "East Asian"
    SAS: "South Asian"
  SUB:
    ASW: "African ancestry in SW USA"
    ACB: "African Caribbean in Barbados"
    BEB: "Bengali in Bangladesh"
    GBR: "British from England and Scotland"
    CDX: "Chinese Dai in Xishuangbanna, China"
    CLM: "Colombian in Medellín, Colombia"
    ESN: "Esan in Nigeria"
    FIN: "Finnish in Finland"
    GWD: "Gambian in Western Division – Mandinka"
    GIH: "Gujarati Indians in Houston, Texas, United States"
    CHB: "Han Chinese in Beijing, China"
    CHS: "Han Chinese South, China"
    IBS: "Iberian populations in Spain"
    ITU: "Indian Telugu in the U.K."
    JPT: "Japanese in Tokyo, Japan"
    KHV: "Kinh in Ho Chi Minh City, Vietnam"
    LWK: "Luhya in Webuye, Kenya"
    MSL: "Mende in Sierra Leone"
    MXL: "Mexican Ancestry in Los Angeles CA United States"
    PEL: "Peruvian in Lima, Peru"
    PUR: "Puerto Rican in Puerto Rico"
    PJL: "Punjabi in Lahore, Pakistan"
    STU: "Sri Lankan Tamil in the UK"
    TSI: "Toscani in Italia"
    YRI: "Yoruba in Ibadan, Nigeria"
    CEU: "Utah residents with Northern and Western European ancestry from the CEPH collection"
